### ISSUE TITLE
Declarative interface HasStatus would ease position handling

### ISSUE THREAD

**Issue by foosmate** [amsa-code/risky#141]
Since there are multiple classes providing a `NavigationalStatus` it would ease the message handling if there is an interface like this ...

    public interface HasStatus {
        NavigationalStatus getNavigationalStatus();
    }

    public class AisPositionA implements AisPosition, HasCommunications, HasStatus {
    ...
    }

    public class AisPositionGPS implements AisPosition, HasStatus {
    ...
    }

**Comment by davidmoten** [comment]
Sounds fine, will do.

**Comment by davidmoten** [comment]
This is in release [0.6.15](https://github.com/amsa-code/risky/releases/tag/0.6.15) on Maven Central now.
